# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - '**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        game_version: [ 'mists', 'retail' ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install lua dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install luarocks subversion
          sudo luarocks install luaunit
          sudo luarocks install luacov
          sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck addon

      - name: Build the addon
        uses: BigWigsMods/packager@v2.4.3
        with:
          args: -g ${{ matrix.game_version }} -z -d

      - name: Move libraries and compiled metadata files
        run: |
          mv .release/BattlePetQualityCheck/libs .
          mv .release/BattlePetQualityCheck/BattlePetQualityCheck.toc .

      - name: Run tests
        run: for test in test*.lua; do lua -lluacov "$test"; done
        working-directory: tests
        env:
          GAME_VERSION: ${{ matrix.game_version }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          path: 'addon'
          annotate: warning

      - name: WoW Packager
        uses: BigWigsMods/packager@v2.4.3
